#!/usr/bin/env python3
"""
自动从订阅源下载 Tracker 列表，合并去重后写入本地仓库，
并生成 GitHub Pages 短链接重定向页面、服务主页与多 CDN 镜像清单。

订阅源:
  - https://cf.trackerslist.com/best.txt
  - https://cf.trackerslist.com/http.txt
  - https://trackers.run/s/rw_ws_up_hp_hs_v4_v6.txt
"""

import os
import sys
import time
import html
import urllib.request
import datetime

SOURCES = [
    ("trackers_best.txt", "https://cf.trackerslist.com/best.txt"),
    ("trackers_http.txt", "https://cf.trackerslist.com/http.txt"),
    ("trackers_run.txt", "https://trackers.run/s/rw_ws_up_hp_hs_v4_v6.txt"),
]

MIRRORS = [
    ("GitHub Raw", "https://raw.githubusercontent.com/{repo}/main/trackers/{file}"),
    ("jsDelivr CDN", "https://cdn.jsdelivr.net/gh/{repo}@main/trackers/{file}"),
    ("jsDelivr Fastly", "https://fastly.jsdelivr.net/gh/{repo}@main/trackers/{file}"),
    ("jsDelivr Gcore", "https://gcore.jsdelivr.net/gh/{repo}@main/trackers/{file}"),
    ("ghproxy", "https://ghproxy.net/https://raw.githubusercontent.com/{repo}/main/trackers/{file}"),
    ("gh-proxy", "https://gh-proxy.com/https://raw.githubusercontent.com/{repo}/main/trackers/{file}"),
]

SHORT_LINKS = [
    ("alive",      "核心订阅", "存活 Tracker（经活性测试，最推荐）",
     "https://raw.githubusercontent.com/{repo}/main/trackers/trackers_alive.txt"),
    ("alive-cdn",  "核心订阅", "存活 Tracker（jsDelivr CDN）",
     "https://cdn.jsdelivr.net/gh/{repo}@main/trackers/trackers_alive.txt"),
    ("best",       "核心订阅", "最佳 Tracker 列表（best）",
     "https://raw.githubusercontent.com/{repo}/main/trackers/trackers_best.txt"),
    ("http",       "核心订阅", "HTTP/HTTPS Tracker 列表",
     "https://raw.githubusercontent.com/{repo}/main/trackers/trackers_http.txt"),
    ("run",        "核心订阅", "混合 Tracker 列表（trackers.run）",
     "https://raw.githubusercontent.com/{repo}/main/trackers/trackers_run.txt"),
    ("all",        "核心订阅", "合并总表（Raw 直连）",
     "https://raw.githubusercontent.com/{repo}/main/trackers/trackers_merged.txt"),
    ("all-cdn",     "核心订阅", "合并总表（jsDelivr CDN）",
     "https://cdn.jsdelivr.net/gh/{repo}@main/trackers/trackers_merged.txt"),
    ("all-fastly",  "核心订阅", "合并总表（Fastly）",
     "https://fastly.jsdelivr.net/gh/{repo}@main/trackers/trackers_merged.txt"),
    ("all-gcore",   "核心订阅", "合并总表（Gcore）",
     "https://gcore.jsdelivr.net/gh/{repo}@main/trackers/trackers_merged.txt"),
    ("all-proxy",   "核心订阅", "合并总表（ghproxy）",
     "https://ghproxy.net/https://raw.githubusercontent.com/{repo}/main/trackers/trackers_merged.txt"),
    ("repo", "其他", "GitHub 仓库主页", "https://github.com/{repo}"),
]

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_DIR = os.path.join(PROJECT_ROOT, "trackers")
PAGES_DIR = os.path.join(PROJECT_ROOT, "docs")
SHORT_LINKS_DIR = os.path.join(PAGES_DIR, "s")
MERGED_FILE = "trackers_merged.txt"
ALIVE_FILE = "trackers_alive.txt"
DEAD_FILE = "trackers_dead.txt"
TIMEOUT = 30
MAX_RETRIES = 3
RETRY_DELAY = 5


def get_repo():
    repo = os.environ.get("GITHUB_REPOSITORY", "").strip()
    return repo if repo else "Pmwiu/Tracker-List"


def download_trackers(url):
    last_error = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "trackers-list-bot/1.0"})
            with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
                raw = resp.read().decode("utf-8", errors="replace")
            break
        except Exception as e:
            last_error = e
            if attempt < MAX_RETRIES:
                print(f"  [RETRY] {attempt}/{MAX_RETRIES}: {e}")
                time.sleep(RETRY_DELAY)
            else:
                raise last_error
    trackers = set()
    for line in raw.splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            trackers.add(line)
    return sorted(trackers)


def write_trackers(filepath, trackers, source_url=None):
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    h = ["# Auto-generated by update_trackers.py", f"# Last updated: {now} UTC"]
    if source_url:
        h.append(f"# Source: {source_url}")
    h.append(f"# Total unique trackers: {len(trackers)}")
    h.append("")
    with open(filepath, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(h) + "\n".join(trackers) + "\n")


def write_mirrors_file(repo):
    lines = ["# Tracker 订阅镜像清单",
             f"# Generated: {datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC",
             "# 默认链接不可用时依次尝试：", ""]
    for name, template in MIRRORS:
        lines.append(f"# [{name}]")
        lines.append(template.format(repo=repo, file=MERGED_FILE))
        lines.append("")
    with open(os.path.join(OUTPUT_DIR, "MIRRORS.txt"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"[OK] MIRRORS.txt ({len(MIRRORS)} mirrors)")


def generate_redirect_page(target_url, description=""):
    e = html.escape(target_url, quote=True)
    d = html.escape(description)
    return f"""<!DOCTYPE html>
<html lang="zh-CN"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="refresh" content="0; url={e}">
<link rel="canonical" href="{e}">
<title>Redirecting... | Tracker List</title>
<style>
body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;display:flex;
justify-content:center;align-items:center;min-height:100vh;margin:0;background:#0d1117;color:#c9d1d9}}
.box{{text-align:center;padding:2rem}}
.sp{{width:40px;height:40px;border:3px solid #30363d;border-top-color:#58a6ff;border-radius:50%;
animation:sp .8s linear infinite;margin:0 auto 1.5rem}}
@keyframes sp{{to{{transform:rotate(360deg)}}}}
a{{color:#58a6ff}}
</style></head><body><div class="box"><div class="sp"></div>
<p>{d}</p><p>If not redirected, <a href="{e}">click here</a>.</p></div>
<script>window.location.replace("{e}");</script></body></html>
"""


def generate_index_page(repo, short_links_with_urls, tracker_counts):
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    owner = repo.split("/")[0]
    rn = repo.split("/")[-1]
    pages_base = f"https://{owner}.github.io/{rn}"
    groups = {}
    for short, group, desc, target in short_links_with_urls:
        groups.setdefault(group, []).append((short, desc, target))
    sections_html = ""
    for group_name in ["核心订阅", "分类列表", "其他"]:
        items = groups.get(group_name, [])
        if not items:
            continue
        cards = ""
        for short, desc, target in items:
            short_url = f"{pages_base}/s/{short}"
            cards += (f'<div class="lc"><div class="ls"><a href="{short_url}">{short_url}</a></div>'
                      f'<div class="ld">{html.escape(desc)}</div>'
                      f'<div class="lt">&#8594; {html.escape(target)}</div></div>\n')
        sections_html += f'<section><h2>{group_name}</h2>{cards}</section>\n'
    counts_rows = "".join(
        f"<tr><td>{html.escape(n)}</td><td>{c}</td></tr>\n" for n, c in tracker_counts)
    return f"""<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Tracker List - Auto Subscription</title>
<style>
*{{box-sizing:border-box;margin:0;padding:0}}
body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#0d1117;
color:#c9d1d9;line-height:1.6}}
.c{{max-width:820px;margin:0 auto;padding:2rem 1.5rem}}
header{{text-align:center;padding:3rem 0 2rem}}
h1{{font-size:2rem;color:#f0f6fc;margin-bottom:.5rem}}
.sub{{color:#8b949e}}
.bd{{margin-top:.8rem}}
.b{{display:inline-block;background:#238636;color:#fff;font-size:.75rem;padding:.2rem .6rem;
border-radius:12px;margin:0 .2rem}}
.b.bl{{background:#1f6feb}}
section{{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:1.5rem;margin-bottom:1.5rem}}
h2{{font-size:1.15rem;color:#f0f6fc;margin-bottom:1rem;padding-bottom:.5rem;border-bottom:1px solid #21262d}}
.lc{{padding:.8rem 0;border-bottom:1px solid #21262d}}
.lc:last-child{{border-bottom:none}}
.ls a{{color:#58a6ff;text-decoration:none;font-weight:600;word-break:break-all}}
.ls a:hover{{text-decoration:underline}}
.ld{{font-size:.9rem;margin-top:.2rem}}
.lt{{color:#8b949e;font-size:.78rem;margin-top:.2rem;word-break:break-all}}
table{{width:100%;border-collapse:collapse;font-size:.9rem}}
th,td{{text-align:left;padding:.5rem .75rem;border-bottom:1px solid #21262d}}
th{{color:#8b949e;font-weight:600}}
td:last-child{{text-align:right;font-variant-numeric:tabular-nums}}
.u{{background:#0d1117;border:1px solid #30363d;border-radius:6px;padding:1rem;font-family:monospace;
font-size:.85rem;color:#7ee787;margin-top:.5rem;word-break:break-all}}
.ft{{text-align:center;color:#484f58;font-size:.8rem;padding:2rem 0}}
.ft a{{color:#58a6ff;text-decoration:none}}
</style></head><body><div class="c">
<header><h1>Tracker List</h1><p class="sub">Auto Subscription &middot; Deduplicated &middot; Short Links &middot; Multi-CDN</p>
<div class="bd"><span class="b">7x24H Auto Update</span><span class="b bl">DNS Anti-Pollution</span>
<span class="b bl">Multi-CDN Failover</span></div></header>
{sections_html}<section><h2>Tracker Statistics</h2>
<table><thead><tr><th>List</th><th>Count</th></tr></thead><tbody>{counts_rows}</tbody></table></section>
<section><h2>Quick Start</h2><p>Copy into your BitTorrent client:</p>
<div class="u">{pages_base}/s/alive</div>
<p style="margin-top:.8rem;font-size:.88rem;color:#8b949e">
<code style="color:#7ee787">/s/alive</code> contains only trackers that passed the liveness test.
Full list: <code style="color:#7ee787">/s/all</code>.</p></section>
<div class="ft"><p>Updated: {now}</p>
<p>Sources: <a href="https://cf.trackerslist.com/best.txt">cf.trackerslist.com</a> &middot;
<a href="https://trackers.run/s/rw_ws_up_hp_hs_v4_v6.txt">trackers.run</a> &middot;
Repo: <a href="https://github.com/{repo}">{repo}</a></p></div>
</div></body></html>"""


def generate_pages(repo, results):
    os.makedirs(SHORT_LINKS_DIR, exist_ok=True)
    short_links_with_urls = []
    for short, group, desc, template in SHORT_LINKS:
        target = template.format(repo=repo)
        short_links_with_urls.append((short, group, desc, target))
        with open(os.path.join(SHORT_LINKS_DIR, f"{short}.html"), "w", encoding="utf-8", newline="\n") as f:
            f.write(generate_redirect_page(target, desc))
        print(f"[OK] /s/{short}")
    with open(os.path.join(PAGES_DIR, "index.html"), "w", encoding="utf-8", newline="\n") as f:
        f.write(generate_index_page(repo, short_links_with_urls, results))
    nj = os.path.join(PAGES_DIR, ".nojekyll")
    if not os.path.exists(nj):
        open(nj, "w").close()
    print("[OK] index.html")


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    repo = get_repo()
    print(f"[INFO] Repo: {repo}")
    all_merged = set()
    results = []
    for filename, url in SOURCES:
        print(f"[INFO] {filename}")
        try:
            trackers = download_trackers(url)
        except Exception as e:
            print(f"[ERROR] {filename}: {e}", file=sys.stderr)
            if os.path.exists(os.path.join(OUTPUT_DIR, filename)):
                print(f"[WARN] keeping existing {filename}")
            continue
        write_trackers(os.path.join(OUTPUT_DIR, filename), trackers, url)
        all_merged.update(trackers)
        results.append((filename, len(trackers)))
        print(f"[OK] {filename}: {len(trackers)}")
    if all_merged:
        ms = sorted(all_merged)
        write_trackers(os.path.join(OUTPUT_DIR, MERGED_FILE), ms, ", ".join(u for _, u in SOURCES))
        results.append((MERGED_FILE, len(ms)))
        print(f"[OK] merged: {len(ms)}")
    write_mirrors_file(repo)
    print("\n[INFO] Pages...")
    generate_pages(repo, results)
    print("\n===== Summary =====")
    for n, c in results:
        print(f"  {n}: {c}")
    print("===================")
    if not results:
        sys.exit(1)


if __name__ == "__main__":
    main()
