#!/usr/bin/env python3
"""
自动从订阅源下载 Tracker 列表，合并去重后写入本地仓库，
并生成 GitHub Pages 短链接重定向页面、服务主页与纯文本订阅文件。

订阅源（均为 best 精选列表）:
  - https://cf.trackerslist.com/best.txt
  - https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt
  - https://tracker.adysec.com/trackers_best.txt

特性:
  - 多源合并去重
  - 活性测试后按响应速度排序，最终总数不超过 89
  - 仅保留 GitHub Raw 直链与 Pages 短链接，无 CDN/代理加速链接
  - 纯文本 .txt 直链供 BT 客户端直接订阅
"""

import os
import sys
import time
import html
import urllib.request
import datetime

SOURCES = [
    ("trackers_best.txt", "https://cf.trackerslist.com/best.txt", "cf-best"),
    ("trackers_ngosang.txt", "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt", "ngosang-best"),
    ("trackers_adysec.txt", "https://tracker.adysec.com/trackers_best.txt", "adysec-best"),
]

MAX_TRACKERS = 89

MIRRORS = [
    ("GitHub Raw 直连", "https://raw.githubusercontent.com/{repo}/main/trackers/{file}"),
]

SHORT_LINKS = [
    ("alive", "核心订阅", "存活 Tracker（经活性测试+测速排序，最推荐）",
     "https://raw.githubusercontent.com/{repo}/main/trackers/trackers_alive.txt"),
    ("best", "订阅源", "cf.trackerslist.com best 列表",
     "https://raw.githubusercontent.com/{repo}/main/trackers/trackers_best.txt"),
    ("ngosang", "订阅源", "ngosang trackers_best 列表",
     "https://raw.githubusercontent.com/{repo}/main/trackers/trackers_ngosang.txt"),
    ("adysec", "订阅源", "adysec trackers_best 列表",
     "https://raw.githubusercontent.com/{repo}/main/trackers/trackers_adysec.txt"),
    ("all", "合并总表", "合并去重总表（Raw 直连）",
     "https://raw.githubusercontent.com/{repo}/main/trackers/trackers_merged.txt"),
    ("repo", "其他", "GitHub 仓库主页", "https://github.com/{repo}"),
]

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_DIR = os.path.join(PROJECT_ROOT, "trackers")
PAGES_DIR = os.path.join(PROJECT_ROOT, "docs")
SHORT_LINKS_DIR = os.path.join(PAGES_DIR, "s")
MERGED_FILE = "trackers_merged.txt"
ALIVE_FILE = "trackers_alive.txt"
DEAD_FILE = "trackers_dead.txt"

LEGACY_FILES = [
    os.path.join(OUTPUT_DIR, "trackers_http.txt"),
    os.path.join(OUTPUT_DIR, "trackers_all.txt"),
    os.path.join(OUTPUT_DIR, "trackers_run.txt"),
    os.path.join(PAGES_DIR, "http.txt"),
    os.path.join(PAGES_DIR, "full.txt"),
    os.path.join(SHORT_LINKS_DIR, "http.html"),
    os.path.join(SHORT_LINKS_DIR, "full.html"),
    os.path.join(SHORT_LINKS_DIR, "run.html"),
    os.path.join(SHORT_LINKS_DIR, "alive-cdn.html"),
    os.path.join(SHORT_LINKS_DIR, "all-cdn.html"),
    os.path.join(SHORT_LINKS_DIR, "all-fastly.html"),
    os.path.join(SHORT_LINKS_DIR, "all-gcore.html"),
    os.path.join(SHORT_LINKS_DIR, "all-proxy.html"),
]

TIMEOUT = 30
MAX_RETRIES = 3
RETRY_DELAY = 5


def get_repo():
    repo = os.environ.get("GITHUB_REPOSITORY", "").strip()
    return repo if repo else "Pmwiu/Tracker-List"


def cleanup_legacy_files():
    removed = 0
    for path in LEGACY_FILES:
        if os.path.exists(path):
            try:
                os.remove(path)
                print(f"[CLEAN] Removed: {os.path.relpath(path, PROJECT_ROOT)}")
                removed += 1
            except OSError as e:
                print(f"[WARN]  Failed: {path}: {e}")
    if removed:
        print(f"[OK]   Cleaned {removed} legacy files.")


def download_trackers(url):
    last_error = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "trackers-list-bot/2.0"})
            with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
                raw = resp.read().decode("utf-8", errors="replace")
            break
        except Exception as e:
            last_error = e
            if attempt < MAX_RETRIES:
                print(f"  [RETRY] {attempt}/{MAX_RETRIES} failed: {e}")
                time.sleep(RETRY_DELAY)
            else:
                raise last_error
    trackers = set()
    for line in raw.splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            trackers.add(line)
    return sorted(trackers)


def write_trackers(filepath, trackers, source_url=None, extra_header=None):
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    header = ["# Auto-generated by update_trackers.py", f"# Last updated: {now} UTC"]
    if source_url:
        header.append(f"# Source: {source_url}")
    if extra_header:
        header.append(extra_header)
    header.append(f"# Total unique trackers: {len(trackers)}")
    header.append("")
    with open(filepath, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(header) + "\n".join(trackers) + "\n")


def write_mirrors_file(repo):
    lines = ["# Tracker 订阅地址清单",
             f"# Generated: {datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC",
             "# 仅保留 GitHub Raw 直连，无 CDN/代理加速链接", ""]
    for name, template in MIRRORS:
        url = template.format(repo=repo, file=MERGED_FILE)
        lines += [f"# [{name}]", url, ""]
    with open(os.path.join(OUTPUT_DIR, "MIRRORS.txt"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"[OK]   MIRRORS.txt ({len(MIRRORS)} direct link).")


def generate_redirect_page(target_url, description=""):
    eu = html.escape(target_url, quote=True)
    ed = html.escape(description)
    return f"""<!DOCTYPE html>\n<html lang=\"zh-CN\">\n<head>\n<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n<meta http-equiv=\"refresh\" content=\"0; url={eu}\">\n<link rel=\"canonical\" href=\"{eu}\">\n<title>Redirecting... | Tracker List</title>\n<style>\n  body {{ font-family: -apple-system, sans-serif; display: flex; justify-content: center; align-items: center; min-height: 100vh; margin: 0; background: #0d1117; color: #c9d1d9; }}\n  .box {{ text-align: center; padding: 2rem; }}\n  .spinner {{ width: 40px; height: 40px; border: 3px solid #30363d; border-top-color: #58a6ff; border-radius: 50%; animation: spin 0.8s linear infinite; margin: 0 auto 1.5rem; }}\n  @keyframes spin {{ to {{ transform: rotate(360deg); }} }}\n  a {{ color: #58a6ff; }}\n</style>\n</head>\n<body>\n<div class=\"box\">\n  <div class=\"spinner\"></div>\n  <p>{ed}</p>\n  <p>If not redirected, <a href=\"{eu}\">click here</a>.</p>\n</div>\n<script>window.location.replace(\"{eu}\");</script>\n</body>\n</html>\n"""


def generate_index_page(repo, short_links_with_urls, tracker_counts):
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    owner = repo.split("/")[0] if "/" in repo else repo
    repo_name = repo.split("/")[-1]
    pages_base = f"https://{owner}.github.io/{repo_name}"
    groups = {}
    for short, group, desc, target in short_links_with_urls:
        groups.setdefault(group, []).append((short, desc, target))
    sections_html = ""
    for group_name in ["核心订阅", "订阅源", "合并总表", "其他"]:
        items = groups.get(group_name, [])
        if not items:
            continue
        cards = ""
        for short, desc, target in items:
            su = f"{pages_base}/s/{short}"
            cards += f"        <div class=\"link-card\">\n          <div class=\"link-short\"><a href=\"{html.escape(su)}\">{html.escape(su)}</a></div>\n          <div class=\"link-desc\">{html.escape(desc)}</div>\n          <div class=\"link-target\">&#8594; {html.escape(target)}</div>\n        </div>\n"
        sections_html += f"  <section>\n    <h2>{html.escape(group_name)}</h2>\n{cards}  </section>\n\n"
    counts_rows = ""
    for name, count in tracker_counts:
        counts_rows += f"        <tr><td>{html.escape(name)}</td><td>{count}</td></tr>\n"
    return f"""<!DOCTYPE html>\n<html lang=\"zh-CN\">\n<head>\n<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n<title>Tracker List</title>\n<style>\n  *{{box-sizing:border-box;margin:0;padding:0}}body{{font-family:-apple-system,sans-serif;background:#0d1117;color:#c9d1d9;line-height:1.6}}.container{{max-width:820px;margin:0 auto;padding:2rem 1.5rem}}header{{text-align:center;padding:3rem 0 2rem}}h1{{font-size:2rem;color:#f0f6fc;margin-bottom:.5rem}}.subtitle{{color:#8b949e}}.badges{{margin-top:.8rem}}.badge{{display:inline-block;background:#238636;color:#fff;font-size:.75rem;padding:.2rem .6rem;border-radius:12px;margin:0 .2rem}}.badge.blue{{background:#1f6feb}}section{{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:1.5rem;margin-bottom:1.5rem}}h2{{font-size:1.15rem;color:#f0f6fc;margin-bottom:1rem;padding-bottom:.5rem;border-bottom:1px solid #21262d}}.link-card{{padding:.8rem 0;border-bottom:1px solid #21262d}}.link-card:last-child{{border-bottom:none}}.link-short a{{color:#58a6ff;text-decoration:none;font-weight:600;word-break:break-all}}.link-desc{{color:#c9d1d9;font-size:.9rem;margin-top:.2rem}}.link-target{{color:#8b949e;font-size:.78rem;margin-top:.2rem;word-break:break-all}}table{{width:100%;border-collapse:collapse;font-size:.9rem}}th,td{{text-align:left;padding:.5rem .75rem;border-bottom:1px solid #21262d}}th{{color:#8b949e;font-weight:600}}td:last-child{{text-align:right}}.usage{{background:#0d1117;border:1px solid #30363d;border-radius:6px;padding:1rem;font-family:monospace;font-size:.85rem;overflow-x:auto;color:#7ee787;margin-top:.5rem;word-break:break-all}}.footer{{text-align:center;color:#484f58;font-size:.8rem;padding:2rem 0}}.footer a{{color:#58a6ff;text-decoration:none}}\n</style>\n</head>\n<body>\n<div class=\"container\">\n  <header>\n    <h1>Tracker List</h1>\n    <p class=\"subtitle\">Auto Subscription &middot; Deduplicated &middot; Liveness Tested &middot; Speed Sorted &middot; Max {MAX_TRACKERS}</p>\n    <div class=\"badges\"><span class=\"badge\">7x24H Auto Update</span><span class=\"badge blue\">Speed Top {MAX_TRACKERS}</span><span class=\"badge blue\">Direct Links Only</span></div>\n  </header>\n\n{sections_html}  <section>\n    <h2>Tracker Statistics</h2>\n    <table><thead><tr><th>List</th><th>Count</th></tr></thead><tbody>\n{counts_rows}    </tbody></table>\n  </section>\n\n  <section>\n    <h2>Quick Start</h2>\n    <p>For BT clients, use the <strong>plain-text link</strong>:</p>\n    <div class=\"usage\">{pages_base}/alive.txt</div>\n    <p style=\"margin-top:.8rem;font-size:.88rem;color:#8b949e\"><code style=\"color:#7ee787\">/alive.txt</code> = liveness-tested, speed-sorted, max {MAX_TRACKERS}. Browser: <code style=\"color:#7ee787\">/s/alive</code></p>\n  </section>\n\n  <div class=\"footer\">\n    <p>Last updated: {now}</p>\n    <p>Sources: <a href=\"https://cf.trackerslist.com/best.txt\">cf/best</a> &middot; <a href=\"https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt\">ngosang/best</a> &middot; <a href=\"https://tracker.adysec.com/trackers_best.txt\">adysec/best</a></p>\n  </div>\n</div>\n</body>\n</html>\n"""


def generate_pages(repo, results):
    os.makedirs(SHORT_LINKS_DIR, exist_ok=True)
    sl = []
    for short, group, desc, template in SHORT_LINKS:
        target = template.format(repo=repo)
        sl.append((short, group, desc, target))
        with open(os.path.join(SHORT_LINKS_DIR, f"{short}.html"), "w", encoding="utf-8", newline="\n") as f:
            f.write(generate_redirect_page(target, desc))
        print(f"[OK]   /s/{short}")
    with open(os.path.join(PAGES_DIR, "index.html"), "w", encoding="utf-8", newline="\n") as f:
        f.write(generate_index_page(repo, sl, results))
    print("[OK]   index.html")
    nj = os.path.join(PAGES_DIR, ".nojekyll")
    if not os.path.exists(nj):
        open(nj, "w").close()


def sync_plain_text_files():
    mapping = {"trackers_alive.txt": "alive.txt", "trackers_merged.txt": "merged.txt",
               "trackers_best.txt": "best.txt", "trackers_ngosang.txt": "ngosang.txt",
               "trackers_adysec.txt": "adysec.txt"}
    os.makedirs(PAGES_DIR, exist_ok=True)
    for src, dst in mapping.items():
        sp = os.path.join(OUTPUT_DIR, src)
        if os.path.exists(sp):
            with open(sp, "r", encoding="utf-8") as f:
                content = f.read()
            with open(os.path.join(PAGES_DIR, dst), "w", encoding="utf-8", newline="\n") as f:
                f.write(content)
            print(f"[OK]   docs/{dst}")


def count_trackers_in_text(text):
    return sum(1 for line in text.splitlines() if line.strip() and not line.strip().startswith("#"))


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    repo = get_repo()
    print(f"[INFO] Repo: {repo}, Max: {MAX_TRACKERS}")
    cleanup_legacy_files()
    all_merged = set()
    results = []
    for filename, url, short_name in SOURCES:
        print(f"\n[INFO] {filename} ({short_name})")
        try:
            trackers = download_trackers(url)
        except Exception as e:
            print(f"[ERROR] {e}", file=sys.stderr)
            continue
        write_trackers(os.path.join(OUTPUT_DIR, filename), trackers, source_url=url)
        all_merged.update(trackers)
        results.append((filename, len(trackers)))
        print(f"[OK]   {len(trackers)} unique")
    if all_merged:
        merged = sorted(all_merged)
        write_trackers(os.path.join(OUTPUT_DIR, MERGED_FILE), merged,
                       source_url=", ".join(u for _, u, _ in SOURCES))
        results.append((MERGED_FILE, len(merged)))
        print(f"\n[OK]   merged: {len(merged)}")
    write_mirrors_file(repo)
    generate_pages(repo, results)
    sync_plain_text_files()
    print(f"\n===== Summary =====")
    for n, c in results:
        print(f"  {n}: {c}")
    print(f"  alive capped at {MAX_TRACKERS} after test+sort")
    print("===================")
    if not results:
        sys.exit(1)


if __name__ == "__main__":
    main()
