#!/usr/bin/env python3
"""
自动从公开 GitHub 项目下载 Tracker 列表，合并去重后写入本地仓库，
并生成 GitHub Pages 短链接重定向页面、服务主页与多 CDN 镜像清单。

DNS 防污染策略:
  - GitHub raw 直连（默认）
  - jsDelivr CDN（cdn.jsdelivr.net）
  - jsDelivr Fastly 节点（fastly.jsdelivr.net）
  - jsDelivr Gcore 节点（gcore.jsdelivr.net）
  - ghproxy 代理镜像
  - GitHub Pages 跳转层

数据源: ngosang/trackerslist
"""

import os
import sys
import time
import html
import urllib.request
import datetime

SOURCES = [
    ("trackers_all.txt",
     "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt"),
    ("trackers_all_ip.txt",
     "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all_ip.txt"),
    ("trackers_all_ws.txt",
     "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all_ws.txt"),
    ("trackers_all_i2p.txt",
     "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all_i2p.txt"),
    ("trackers_all_yggdrasil.txt",
     "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all_yggdrasil.txt"),
    ("trackers_all_yggdrasil_ip.txt",
     "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all_yggdrasil_ip.txt"),
]

MIRRORS = [
    ("GitHub Raw", "https://raw.githubusercontent.com/{repo}/main/trackers/{file}"),
    ("jsDelivr CDN", "https://cdn.jsdelivr.net/gh/{repo}@main/trackers/{file}"),
    ("jsDelivr Fastly", "https://fastly.jsdelivr.net/gh/{repo}@main/trackers/{file}"),
    ("jsDelivr Gcore", "https://gcore.jsdelivr.net/gh/{repo}@main/trackers/{file}"),
    ("ghproxy", "https://ghproxy.net/https://raw.githubusercontent.com/{repo}/main/trackers/{file}"),
    ("gh-proxy", "https://gh-proxy.com/https://raw.githubusercontent.com/{repo}/main/trackers/{file}"),
]

SHORT_LINKS = [
    ("all",       "核心订阅", "合并总表（Raw，推荐）",
     "https://raw.githubusercontent.com/{repo}/main/trackers/trackers_merged.txt"),
    ("all-cdn",   "核心订阅", "合并总表（jsDelivr CDN）",
     "https://cdn.jsdelivr.net/gh/{repo}@main/trackers/trackers_merged.txt"),
    ("all-fastly","核心订阅", "合并总表（Fastly）",
     "https://fastly.jsdelivr.net/gh/{repo}@main/trackers/trackers_merged.txt"),
    ("all-gcore", "核心订阅", "合并总表（Gcore）",
     "https://gcore.jsdelivr.net/gh/{repo}@main/trackers/trackers_merged.txt"),
    ("all-proxy", "核心订阅", "合并总表（ghproxy）",
     "https://ghproxy.net/https://raw.githubusercontent.com/{repo}/main/trackers/trackers_merged.txt"),
    ("trackers",  "分类列表", "全部 Tracker",
     "https://raw.githubusercontent.com/{repo}/main/trackers/trackers_all.txt"),
    ("ip",        "分类列表", "IP 类 Tracker",
     "https://raw.githubusercontent.com/{repo}/main/trackers/trackers_all_ip.txt"),
    ("ws",        "分类列表", "WebSocket 类 Tracker",
     "https://raw.githubusercontent.com/{repo}/main/trackers/trackers_all_ws.txt"),
    ("i2p",       "分类列表", "I2P 网络 Tracker",
     "https://raw.githubusercontent.com/{repo}/main/trackers/trackers_all_i2p.txt"),
    ("ygg",       "分类列表", "Yggdrasil 网络 Tracker",
     "https://raw.githubusercontent.com/{repo}/main/trackers/trackers_all_yggdrasil.txt"),
    ("ygg-ip",    "分类列表", "Yggdrasil IP 类 Tracker",
     "https://raw.githubusercontent.com/{repo}/main/trackers/trackers_all_yggdrasil_ip.txt"),
    ("repo",      "其他", "GitHub 仓库主页",
     "https://github.com/{repo}"),
]

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_DIR = os.path.join(PROJECT_ROOT, "trackers")
PAGES_DIR = os.path.join(PROJECT_ROOT, "docs")
SHORT_LINKS_DIR = os.path.join(PAGES_DIR, "s")
MERGED_FILE = "trackers_merged.txt"
TIMEOUT = 30
MAX_RETRIES = 3
RETRY_DELAY = 5


def get_repo():
    repo = os.environ.get("GITHUB_REPOSITORY", "").strip()
    return repo if repo else "Pmwiu/Tracker-List"


def download_trackers(url):
    last_error = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "trackers-list-bot/1.0"})
            with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
                raw = resp.read().decode("utf-8", errors="replace")
            break
        except Exception as e:
            last_error = e
            if attempt < MAX_RETRIES:
                print(f"  [RETRY] {attempt}/{MAX_RETRIES} failed: {e}")
                time.sleep(RETRY_DELAY)
            else:
                raise last_error
    trackers = set()
    for line in raw.splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            trackers.add(line)
    return sorted(trackers)


def write_trackers(filepath, trackers, source_url=None):
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    h = ["# Auto-generated by update_trackers.py", f"# Last updated: {now} UTC"]
    if source_url:
        h.append(f"# Source: {source_url}")
    h.append(f"# Total unique trackers: {len(trackers)}")
    h.append("")
    with open(filepath, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(h) + "\n".join(trackers) + "\n")


def write_mirrors_file(repo):
    lines = ["# Tracker 订阅镜像清单",
             f"# Generated: {datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC",
             "# 默认链接不可用时依次尝试：", ""]
    for name, template in MIRRORS:
        lines.append(f"# [{name}]")
        lines.append(template.format(repo=repo, file=MERGED_FILE))
        lines.append("")
    with open(os.path.join(OUTPUT_DIR, "MIRRORS.txt"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"[OK] MIRRORS.txt ({len(MIRRORS)} mirrors)")


def redirect_page(target, desc):
    e = html.escape(target, quote=True)
    d = html.escape(desc)
    return f"""<!DOCTYPE html>
<html lang="zh-CN"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="refresh" content="0; url={e}">
<link rel="canonical" href="{e}">
<title>Redirecting... | Tracker List</title>
<style>
body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;display:flex;
justify-content:center;align-items:center;min-height:100vh;margin:0;background:#0d1117;color:#c9d1d9}}
.box{{text-align:center;padding:2rem}}
.sp{{width:40px;height:40px;border:3px solid #30363d;border-top-color:#58a6ff;border-radius:50%;
animation:sp .8s linear infinite;margin:0 auto 1.5rem}}
@keyframes sp{{to{{transform:rotate(360deg)}}}}
a{{color:#58a6ff}}
</style></head><body><div class="box"><div class="sp"></div>
<p>{d}</p><p>If not redirected, <a href="{e}">click here</a>.</p></div>
<script>window.location.replace("{e}");</script></body></html>
"""


def index_page(repo, links, counts):
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    owner = repo.split("/")[0]
    rn = repo.split("/")[-1]
    base = f"https://{owner}.github.io/{rn}"
    groups = {}
    for s, g, d, t in links:
        groups.setdefault(g, []).append((s, d, t))
    sec = ""
    for gn in ["核心订阅", "分类列表", "其他"]:
        items = groups.get(gn, [])
        if not items:
            continue
        cards = ""
        for s, d, t in items:
            su = f"{base}/s/{s}"
            cards += (f'<div class="lc"><div class="ls"><a href="{su}">{su}</a></div>'
                      f'<div class="ld">{html.escape(d)}</div>'
                      f'<div class="lt">&#8594; {html.escape(t)}</div></div>\n')
        sec += f'<section><h2>{gn}</h2>{cards}</section>\n'
    rows = "".join(f"<tr><td>{html.escape(n)}</td><td>{c}</td></tr>" for n, c in counts)
    return f"""<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Tracker List - Auto Subscription</title>
<style>
*{{box-sizing:border-box;margin:0;padding:0}}
body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#0d1117;
color:#c9d1d9;line-height:1.6}}
.c{{max-width:820px;margin:0 auto;padding:2rem 1.5rem}}
header{{text-align:center;padding:3rem 0 2rem}}
h1{{font-size:2rem;color:#f0f6fc;margin-bottom:.5rem}}
.sub{{color:#8b949e}}
.bd{{margin-top:.8rem}}
.b{{display:inline-block;background:#238636;color:#fff;font-size:.75rem;padding:.2rem .6rem;
border-radius:12px;margin:0 .2rem}}
.b.bl{{background:#1f6feb}}
section{{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:1.5rem;margin-bottom:1.5rem}}
h2{{font-size:1.15rem;color:#f0f6fc;margin-bottom:1rem;padding-bottom:.5rem;border-bottom:1px solid #21262d}}
.lc{{padding:.8rem 0;border-bottom:1px solid #21262d}}
.lc:last-child{{border-bottom:none}}
.ls a{{color:#58a6ff;text-decoration:none;font-weight:600;word-break:break-all}}
.ls a:hover{{text-decoration:underline}}
.ld{{font-size:.9rem;margin-top:.2rem}}
.lt{{color:#8b949e;font-size:.78rem;margin-top:.2rem;word-break:break-all}}
table{{width:100%;border-collapse:collapse;font-size:.9rem}}
th,td{{text-align:left;padding:.5rem .75rem;border-bottom:1px solid #21262d}}
th{{color:#8b949e}}
td:last-child{{text-align:right;font-variant-numeric:tabular-nums}}
.u{{background:#0d1117;border:1px solid #30363d;border-radius:6px;padding:1rem;font-family:monospace;
font-size:.85rem;color:#7ee787;margin-top:.5rem;word-break:break-all}}
.ft{{text-align:center;color:#484f58;font-size:.8rem;padding:2rem 0}}
.ft a{{color:#58a6ff;text-decoration:none}}
</style></head><body><div class="c">
<header><h1>Tracker List</h1><p class="sub">Auto Subscription &middot; Deduplicated &middot; Short Links &middot; Multi-CDN</p>
<div class="bd"><span class="b">7x24H Auto Update</span><span class="b bl">DNS Anti-Pollution</span>
<span class="b bl">Multi-CDN Failover</span></div></header>
{sec}<section><h2>Tracker Statistics</h2>
<table><thead><tr><th>List</th><th>Count</th></tr></thead><tbody>{rows}</tbody></table></section>
<section><h2>Quick Start</h2><p>Copy into your BitTorrent client:</p>
<div class="u">{base}/s/all</div>
<p style="margin-top:.8rem;font-size:.88rem;color:#8b949e">Blocked? Try:
<code style="color:#7ee787">/s/all-cdn</code>, <code style="color:#7ee787">/s/all-fastly</code>,
<code style="color:#7ee787">/s/all-gcore</code>, <code style="color:#7ee787">/s/all-proxy</code>.</p></section>
<div class="ft"><p>Updated: {now}</p>
<p>Source: <a href="https://github.com/ngosang/trackerslist">ngosang/trackerslist</a> &middot;
Repo: <a href="https://github.com/{repo}">{repo}</a></p></div>
</div></body></html>"""


def generate_pages(repo, results):
    os.makedirs(SHORT_LINKS_DIR, exist_ok=True)
    links = []
    for s, g, d, template in SHORT_LINKS:
        t = template.format(repo=repo)
        links.append((s, g, d, t))
        with open(os.path.join(SHORT_LINKS_DIR, f"{s}.html"), "w", encoding="utf-8", newline="\n") as f:
            f.write(redirect_page(t, d))
        print(f"[OK] /s/{s}")
    with open(os.path.join(PAGES_DIR, "index.html"), "w", encoding="utf-8", newline="\n") as f:
        f.write(index_page(repo, links, results))
    nj = os.path.join(PAGES_DIR, ".nojekyll")
    if not os.path.exists(nj):
        open(nj, "w").close()
    print("[OK] index.html")


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    repo = get_repo()
    print(f"[INFO] Repo: {repo}")
    merged = set()
    results = []
    for fn, url in SOURCES:
        print(f"[INFO] {fn}")
        try:
            tr = download_trackers(url)
        except Exception as e:
            print(f"[ERROR] {fn}: {e}", file=sys.stderr)
            if os.path.exists(os.path.join(OUTPUT_DIR, fn)):
                print(f"[WARN] keeping existing {fn}")
            continue
        write_trackers(os.path.join(OUTPUT_DIR, fn), tr, url)
        merged.update(tr)
        results.append((fn, len(tr)))
        print(f"[OK] {fn}: {len(tr)}")
    if merged:
        ms = sorted(merged)
        write_trackers(os.path.join(OUTPUT_DIR, MERGED_FILE), ms,
                       ", ".join(u for _, u in SOURCES))
        results.append((MERGED_FILE, len(ms)))
        print(f"[OK] merged: {len(ms)}")
    write_mirrors_file(repo)
    print("\n[INFO] Pages...")
    generate_pages(repo, results)
    print("\n===== Summary =====")
    for n, c in results:
        print(f"  {n}: {c}")
    print("===================")
    if not results:
        sys.exit(1)


if __name__ == "__main__":
    main()
